version: "3"
services:
  jsp:
    build: ./jsp
    container_name: jsp-server
    volumes:
      - ./jsp/:/usr/local/tomcat/webapps/webapp
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    privileged: true

  mysql:
    image: mysql
    container_name: jsp-sql-server
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "somepassword"
    volumes:
      - ./sql/db-storage:/var/lib/mysql

  import_data:
    build: ./import-data
    container_name: python_import_to_database
    volumes:
      - ./import-data/:/usr/local/app
    stdin_open: true
    tty: true
